# Generated by Django 5.0.1 on 2024-01-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_owner_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10, verbose_name='Gender'),
        ),
    ]
