# Generated by Django 5.0.1 on 2024-01-17 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_owner_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Desk Number')),
                ('floor', models.SmallIntegerField(verbose_name='Floor No.')),
            ],
            options={
                'ordering': ['floor', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('IN', 'Intern'), ('EP', 'Employee')], max_length=20)),
                ('desk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.desk')),
            ],
        ),
    ]
