# Generated by Django 5.0.1 on 2024-01-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_customer_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmyMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Civilian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
            ],
        ),
    ]
