from typing import Any
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.urls import reverse_lazy
from django.http.response import HttpResponse as HttpResponse
from django.utils import timezone
from django.shortcuts import render,redirect,reverse
from django.views.generic import TemplateView, RedirectView, DetailView, ListView, FormView, CreateView,      DeleteView
from home.models import Book
from home.forms import BookForm
# Create your views here.

class Home(TemplateView):
    '''
        Derived From TemplateResponseMixin, ContextMixin, View
    '''
    template_name = "home/t1.html"
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['message'] = "Hello, this Message is generated by get_context_data"

        return context

class Home2(RedirectView):
    '''
        Can be used to redirect to another urls :
        Can be temporary(default) with status code (302)/permanent
        For example : temporary while mantainence of website
    '''
    url = "/"
    # Can be used to perform some logic before redirecting
    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str | None:
        '''
            logic before redirecting
        '''
        if kwargs['id'] > 10:
            return reverse_lazy("formBook")
        else:
            return super().get_redirect_url(*args,**kwargs)
    # pattern_name = 'home:home'
    
class Home3(DetailView):
    '''
        This View type is used for displaying info of a single instance of a model
        By default the target template is appName/modelName_detail.html
        context_object_name is used to specify the object name (default object)

    '''
    model = Book
    template_name = "home/t1.html"
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["time"] = timezone.now()
        return context

'''
    Similarly List view is used for displaying list of objects from the table

    Featuters like pagination, queryset added by the MultipleObjectMixin Class
'''
class Home4(ListView):
    model = Book
    template_name = "home/t2.html"
    ordering = ["pageNo"]
    queryset = Book.objects.all()
    paginate_by = 1

class Home5(FormView):
    template_name = "home/t3.html"
    form_class = BookForm
    # success_url = reverse_lazy("successForm")

    def form_valid(self, form: Any) -> HttpResponse:
        print(form.clean())
        form.save()
        return render(self.request, "home/t4.html",{"form" : form.clean()})
    
class Home6(TemplateView):
    template_name = "home/t4.html"

class Home7(CreateView):
    form_class = BookForm
    template_name = 'home/t3.html'

    success_url = reverse_lazy("bookList")
    pass
    

class Home8(DeleteView):
    model = Book
    template_name = "home/t5.html"
    success_url = reverse_lazy("bookList")

class Home9(RedirectView):
    def get_redirect_url(self, *args: Any, **kwargs: Any) -> str | None:
        try: 
            b = Book.objects.get(id=kwargs.get("pk"))
            url = f"delete/{int(kwargs.get("pk"))}"
            # return reverse("home:DeleteBook",args= [kwargs.get("pk")])
            return url
        except:
            return reverse_lazy("bookList")